### ISSUE TITLE
WCONTINUED undeclared

### ISSUE THREAD

**Issue by Spacelight42** [xkollar/starcrack#1]
Hi, I have problems to compile it, when I run "make" command I get this:

`starcrack.c: In function ‘checkpass’:
starcrack.c:56:42: error: ‘WCONTINUED’ undeclared (first use in this function)
   56 |   w = waitpid(cpid, &status, WUNTRACED | WCONTINUED);
      |                                          ^~~~~~~~~~
starcrack.c:56:42: note: each undeclared identifier is reported only once for each function it appears in
starcrack.c: In function ‘crack_start’:
starcrack.c:275:2: warning: implicit declaration of function ‘raise’ [-Wimplicit-function-declaration]
  275 |  raise(SIGALRM);
      |  ^~~~~
starcrack.c:275:8: error: ‘SIGALRM’ undeclared (first use in this function)
  275 |  raise(SIGALRM);
      |        ^~~~~~~
starcrack.c: In function ‘init’:
starcrack.c:354:3: warning: ignoring return value of ‘fscanf’, declared with attribute warn_unused_result [-Wunused-result]
  354 |   fscanf(totest, "%s", (char*)&test);
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make: *** [Makefile:10: starcrack] Chyba 1
`

I have 5.15.0-76-generic #83\~20.04.1-Ubuntu x86_64
and 
gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.1)

**Comment by xkollar** [comment]
While I don't have a Ubuntu box lying around, seems there were bunch of changes around structure of headers... I have added some includes to make it work/compile for me... can you try with current master?

Also: "Chyba 1"? 🤪

**Comment by Spacelight42** [comment]
it works now, thanks
